# Generated by Django 4.2.4 on 2023-08-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DewataItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surfspot', models.CharField(default='Dewata', max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.CharField(default='08:30 AM', max_length=20)),
                ('swell1_height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('swell1_period', models.PositiveIntegerField()),
                ('swell2_height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('swell2_period', models.PositiveIntegerField()),
                ('swell3_height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('swell3_period', models.PositiveIntegerField()),
            ],
        ),
    ]
